spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.1.1.1/user-center
    username: root
    password: xxxx
  session:
    timeout: 1000000
server:
  address: 0.0.0.0
#失效时间
